### ISSUE TITLE
Is this related with the reinforcement learning?

### ISSUE THREAD

**Issue by acgtyrant** [metal-crow/Dark-Souls-PvP-AI#18]
I am interested at the reinforcement learning now.

**Comment by acgtyrant** [comment]
By the way, what about training the AI to defeat some BOSS? Is it need to use reinforcement learning?

**Comment by metal-crow** [comment]
Unfortunately, i don't really know what reinforcement learning is myself (^～^;)ゞ, most of my work here is with the basics of neural networks (structural and backpropigation), and besides, i use a library for the real heavy lifting. I'm not even fit to recommend a good learning point!

As for training the AI to defeat a boss, unfortunately, since bosses obey completely different restrictions from players (no backstabs, different stamina systems, different poise systems, drastically different attack types, ec), modifying this AI to fight bosses would be much more involved that just adjusting the neural networks used. You'd have to do some minor restructuring on the AI combat systems.

Also, its really hard to do training with dark souls since there's no way to do acceleration, you have to train the AI at the game speed, which takes A G E S.

**Comment by acgtyrant** [comment]
Thank you for your respone.
